[package]
name = "actix-test-errorhandlers"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-files = "0.1"
actix-rt = "0.2.2"
actix-web = { version = "1.0", default-features = false, features = [] }
